import { Metadata } from "next";
import { Slide, ToastContainer } from "react-toastify";

import "@/assets/styles/index.scss";

import { exo2, roboto } from "@/assets/fonts/fonts";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { MainBgColor } from "@/components/MainBgCollor/MainBgColor";
import StoreProvider from "@/store/components/StoreProvider/StoreProvider";

export const metadata: Metadata = {
  title: "Nixbuy",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${exo2.variable}`}>
      <body>
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "1920",
            height: "1563",
            zIndex: -1,
          }}
        >
          <MainBgColor />
        </div>
        <StoreProvider>
          <>
            <div className="main__container">
              <Header />
              {children}
              <Footer />
            </div>
          </>
        </StoreProvider>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
          transition={Slide}
        />
      </body>
    </html>
  );
}
